# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTryaddtocart():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tryaddtocart(self):
    self.driver.get("http://mys01.fit.vutbr.cz:8084/")
    self.driver.set_window_size(2235, 1257)
    self.driver.find_element(By.LINK_TEXT, "iPhone").click()
    self.driver.find_element(By.ID, "button-cart").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-inverse").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-end > a:nth-child(1) > strong").click()
    self.driver.find_element(By.CSS_SELECTOR, ".float-end > .btn").click()
    self.driver.find_element(By.ID, "button-register").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.ID, "button-register")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
